# pVerify API Tables
# Common data structures and reference tables for pVerify Healthcare Eligibility API

# HTTP Status Codes
http_status_codes = [
    {"code": 200, "status": "OK", "description": "Request successful"},
    {"code": 201, "status": "Created", "description": "Resource created successfully"},
    {"code": 400, "status": "Bad Request", "description": "Invalid request parameters"},
    {"code": 401, "status": "Unauthorized", "description": "Authentication required"},
    {"code": 403, "status": "Forbidden", "description": "Access denied"},
    {"code": 404, "status": "Not Found", "description": "Resource not found"},
    {"code": 409, "status": "Conflict", "description": "Request conflicts with current state"},
    {"code": 429, "status": "Too Many Requests", "description": "Rate limit exceeded"},
    {"code": 500, "status": "Internal Server Error", "description": "Server error"},
    {"code": 502, "status": "Bad Gateway", "description": "Invalid response from upstream server"},
    {"code": 503, "status": "Service Unavailable", "description": "Service temporarily unavailable"}
]

# API Error Codes (Common healthcare eligibility API errors)
api_error_codes = [
    {"code": "E001", "message": "Invalid patient demographics", "description": "Patient name, DOB, or member ID is invalid"},
    {"code": "E002", "message": "Payer not found", "description": "Insurance payer could not be identified"},
    {"code": "E003", "message": "Service type not covered", "description": "Requested service type is not covered by plan"},
    {"code": "E004", "message": "Authorization required", "description": "Prior authorization needed for service"},
    {"code": "E005", "message": "Eligibility expired", "description": "Patient eligibility has expired"},
    {"code": "E006", "message": "Invalid NPI", "description": "Provider NPI is invalid or not recognized"},
    {"code": "E007", "message": "Deductible not met", "description": "Patient has not met annual deductible"},
    {"code": "E008", "message": "Out of network", "description": "Provider is not in patient's network"},
    {"code": "E009", "message": "Benefit limit exceeded", "description": "Annual or lifetime benefit limit reached"},
    {"code": "E010", "message": "Invalid service date", "description": "Service date is invalid or in the future"}
]

# Insurance Payer Types
payer_types = [
    {"code": "COM", "name": "Commercial", "description": "Commercial insurance plans"},
    {"code": "MED", "name": "Medicare", "description": "Medicare plans"},
    {"code": "MCD", "name": "Medicaid", "description": "Medicaid plans"},
    {"code": "MA", "name": "Medicare Advantage", "description": "Medicare Advantage plans"},
    {"code": "WC", "name": "Workers Compensation", "description": "Workers compensation insurance"},
    {"code": "AUTO", "name": "Auto Insurance", "description": "Automobile insurance"},
    {"code": "OTH", "name": "Other", "description": "Other insurance types"}
]

# Coverage Status Codes
coverage_status = [
    {"code": "1", "status": "Active Coverage", "description": "Patient has active coverage"},
    {"code": "2", "status": "Active - Full Risk Capitation", "description": "Active coverage with full risk capitation"},
    {"code": "3", "status": "Active - Services Capitated", "description": "Active coverage with services capitated"},
    {"code": "4", "status": "Active - Services Capitated to Primary Care Physician", "description": "Services capitated to PCP"},
    {"code": "5", "status": "Active - Pending Investigation", "description": "Coverage active but under investigation"},
    {"code": "6", "status": "Inactive", "description": "Coverage is inactive"},
    {"code": "7", "status": "Eligible", "description": "Patient is eligible for coverage"},
    {"code": "8", "status": "Co-Insurance", "description": "Coverage includes co-insurance"},
    {"code": "A", "status": "Alternate", "description": "Alternate insurance available"},
    {"code": "B", "status": "Coordination of Benefits", "description": "Coordination of benefits required"},
    {"code": "C", "status": "Primary Care Provider", "description": "Primary care provider assigned"},
    {"code": "D", "status": "Excluded", "description": "Service excluded from coverage"}
]

# Service Type Codes (STC) - From pVerify API Documentation
service_type_codes = [
    {"code": "1", "name": "Medical Care"},
    {"code": "2", "name": "Surgical"},
    {"code": "3", "name": "Consultation"},
    {"code": "4", "name": "Diagnostic X-Ray"},
    {"code": "5", "name": "Diagnostic Lab"},
    {"code": "6", "name": "Radiation Therapy"},
    {"code": "7", "name": "Anesthesia"},
    {"code": "8", "name": "Surgical Assistance"},
    {"code": "9", "name": "Other Medical"},
    {"code": "10", "name": "Blood Charges"},
    {"code": "11", "name": "Used Durable Medical Equipment"},
    {"code": "12", "name": "Durable Medical Equipment Purchase"},
    {"code": "13", "name": "Ambulatory Service Center Facility"},
    {"code": "14", "name": "Renal Supplies in the Home"},
    {"code": "15", "name": "Alternate Method Dialysis"},
    {"code": "16", "name": "Chronic Renal Disease (CRD) Equipment"},
    {"code": "17", "name": "Pre-Admission Testing"},
    {"code": "18", "name": "Durable Medical Equipment Rental"},
    {"code": "19", "name": "Pneumonia Vaccine"},
    {"code": "20", "name": "Second Surgical Opinion"},
    {"code": "21", "name": "Third Surgical Opinion"},
    {"code": "22", "name": "Social Work"},
    {"code": "23", "name": "Diagnostic Dental"},
    {"code": "24", "name": "Periodontics"},
    {"code": "25", "name": "Restorative"},
    {"code": "26", "name": "Endodontics"},
    {"code": "27", "name": "Maxillofacial Prosthetics"},
    {"code": "28", "name": "Adjunctive Dental Services"},
    {"code": "30", "name": "Health Benefit Plan Coverage"},
    {"code": "32", "name": "Plan Waiting Period"},
    {"code": "33", "name": "Chiropractic"},
    {"code": "34", "name": "Chiropractic Office Visits"},
    {"code": "35", "name": "Dental Care"},
    {"code": "36", "name": "Dental Crowns"},
    {"code": "37", "name": "Dental Accident"},
    {"code": "38", "name": "Orthodontics"},
    {"code": "39", "name": "Prosthodontics"},
    {"code": "40", "name": "Oral Surgery"},
    {"code": "41", "name": "Routine (Preventive) Dental"},
    {"code": "42", "name": "Home Health Care"},
    {"code": "43", "name": "Home Health Prescriptions"},
    {"code": "44", "name": "Home Health Visits"},
    {"code": "45", "name": "Hospice"},
    {"code": "46", "name": "Respite Care"},
    {"code": "47", "name": "Hospital"},
    {"code": "48", "name": "Hospital - Inpatient"},
    {"code": "49", "name": "Hospital - Room and Board"},
    {"code": "50", "name": "Hospital - Outpatient"},
    {"code": "51", "name": "Hospital - Emergency Accident"},
    {"code": "52", "name": "Hospital - Emergency Medical"},
    {"code": "53", "name": "Hospital - Ambulatory Surgical"},
    {"code": "54", "name": "Long Term Care"},
    {"code": "55", "name": "Major Medical"},
    {"code": "56", "name": "Medically Related Transportation"},
    {"code": "57", "name": "Air Transportation"},
    {"code": "58", "name": "Cabulance"},
    {"code": "59", "name": "Licensed Ambulance Licensed Ambulance"},
    {"code": "60", "name": "General Benefits"},
    {"code": "61", "name": "In-vitro Fertilization"},
    {"code": "62", "name": "MRI/CAT Scan"},
    {"code": "63", "name": "Donor Procedures"},
    {"code": "64", "name": "Acupuncture"},
    {"code": "65", "name": "Newborn Care"},
    {"code": "66", "name": "Pathology"},
    {"code": "67", "name": "Smoking Cessation"},
    {"code": "68", "name": "Well Baby Care"},
    {"code": "69", "name": "Maternity"},
    {"code": "70", "name": "Transplants"},
    {"code": "71", "name": "Audiology Exam"},
    {"code": "72", "name": "Inhalation Therapy"},
    {"code": "73", "name": "Diagnostic Medical"},
    {"code": "74", "name": "Private Duty Nursing"},
    {"code": "75", "name": "Prosthetic Device"},
    {"code": "76", "name": "Dialysis"},
    {"code": "77", "name": "Otological Exam"},
    {"code": "78", "name": "Chemotherapy"},
    {"code": "79", "name": "Allergy Testing"},
    {"code": "80", "name": "Immunizations"},
    {"code": "81", "name": "Routine Physical"},
    {"code": "82", "name": "Family Planning"},
    {"code": "83", "name": "Infertility"},
    {"code": "84", "name": "Abortion"},
    {"code": "85", "name": "AIDS"},
    {"code": "86", "name": "Emergency Services"},
    {"code": "87", "name": "Cancer"},
    {"code": "88", "name": "Pharmacy"},
    {"code": "89", "name": "Free Standing Prescription Drug"},
    {"code": "90", "name": "Mail Order Prescription Drug"},
    {"code": "91", "name": "Brand Name Prescription Drug"},
    {"code": "92", "name": "Generic Prescription Drug"},
    {"code": "93", "name": "Podiatry"},
    {"code": "94", "name": "Podiatry - Office Visits"},
    {"code": "95", "name": "Podiatry - Nursing Home Visits"},
    {"code": "96", "name": "Professional (Physician)"},
    {"code": "97", "name": "Anesthesiologist"},
    {"code": "98", "name": "Professional (Physician) Visit - Office"},
    {"code": "99", "name": "Professional (Physician) Visit - Inpatient"},
    {"code": "A0", "name": "Professional (Physician) Visit - Outpatient"},
    {"code": "A1", "name": "Professional (Physician) Visit - Nursing Home"},
    {"code": "A2", "name": "Professional (Physician) Visit - Skilled Nursing Facility"},
    {"code": "A3", "name": "Professional (Physician) Visit - Home"},
    {"code": "A4", "name": "Psychiatric"},
    {"code": "A5", "name": "Psychiatric - Room and Board"},
    {"code": "A6", "name": "Psychotherapy"},
    {"code": "A7", "name": "Psychiatric - Inpatient"},
    {"code": "A8", "name": "Psychiatric - Outpatient"},
    {"code": "A9", "name": "Rehabilitation"},
    {"code": "AA", "name": "Rehabilitation - Room and Board"},
    {"code": "AB", "name": "Rehabilitation - Inpatient"},
    {"code": "AC", "name": "Rehabilitation - Outpatient"},
    {"code": "AD", "name": "Occupational Therapy"},
    {"code": "AE", "name": "Physical Medicine"},
    {"code": "AF", "name": "Speech Therapy"},
    {"code": "AG", "name": "Skilled Nursing Care"},
    {"code": "AH", "name": "Skilled Nursing Care - Room and Board"},
    {"code": "AI", "name": "Substance Abuse"},
    {"code": "AJ", "name": "Alcoholism"},
    {"code": "AK", "name": "Drug Addiction"},
    {"code": "AL", "name": "Vision (Optometry)"},
    {"code": "AM", "name": "Frames"},
    {"code": "AN", "name": "Routine Exam"},
    {"code": "AO", "name": "Lenses"},
    {"code": "AQ", "name": "Nonmedically Necessary Physical"},
    {"code": "AR", "name": "Experimental Drug Therapy"},
    {"code": "B1", "name": "Burn Care"},
    {"code": "B2", "name": "Bran Name Prescription Drug - Formulary"},
    {"code": "B3", "name": "Bran Name Prescription Drug - Non -Formulary"},
    {"code": "BA", "name": "Independent Medical Evaluation"},
    {"code": "BB", "name": "Partial Hospitalization (Psychiatric)"},
    {"code": "BC", "name": "Day Care (Psychiatric)"},
    {"code": "BD", "name": "Cognitive Therapy"},
    {"code": "BE", "name": "Massage Therapy"},
    {"code": "BF", "name": "Pulmonary Rehabilitation"},
    {"code": "BG", "name": "Cardiac Rehabilitation"},
    {"code": "BH", "name": "Pediatric"},
    {"code": "BI", "name": "Nursery"},
    {"code": "BJ", "name": "Skin"},
    {"code": "BK", "name": "Orthopedic"},
    {"code": "BL", "name": "Cardiac"},
    {"code": "BM", "name": "Lymphatic"},
    {"code": "BN", "name": "Gastrointestinal"},
    {"code": "BP", "name": "Endocrine"},
    {"code": "BQ", "name": "Neurology"},
    {"code": "BR", "name": "Eye"},
    {"code": "BS", "name": "Invasive Procedures"},
    {"code": "BT", "name": "Gynecological"},
    {"code": "BU", "name": "Obsterical"},
    {"code": "BV", "name": "Obsterical/Gynecological"},
    {"code": "BW", "name": "Mail Order Prescription Drug : Brand Name"},
    {"code": "BX", "name": "Mail Order Prescription Drug : Generic"},
    {"code": "BY", "name": "Physician Visit - Office : Sick"},
    {"code": "BZ", "name": "Physician Visit - Office : Well"},
    {"code": "C1", "name": "Coronary Care"},
    {"code": "CA", "name": "Private Duty Nursing - Inpatient"},
    {"code": "CB", "name": "Private Duty Nursing - Home"},
    {"code": "CC", "name": "Surgical Benefits - professional (physician)"},
    {"code": "CD", "name": "Surgical Benefits - Facility"},
    {"code": "CE", "name": "Mental Health Provider - Inpatient"},
    {"code": "CF", "name": "Mental Health Provider - Outpatient"},
    {"code": "CG", "name": "Mental Health Facility - Inpatient"},
    {"

# Eligibility Response Codes
eligibility_response_codes = [
    {"code": "Y", "status": "Yes", "description": "Eligible"},
    {"code": "N", "status": "No", "description": "Not Eligible"},
    {"code": "U", "status": "Unknown", "description": "Eligibility Unknown"},
    {"code": "P", "status": "Pending", "description": "Eligibility Pending"}
]

# Plan Type Codes
plan_types = [
    {"code": "EPO", "name": "Exclusive Provider Organization", "description": "EPO plan type"},
    {"code": "FFS", "name": "Fee For Service", "description": "Fee for service plan"},
    {"code": "HMO", "name": "Health Maintenance Organization", "description": "HMO plan type"},
    {"code": "IND", "name": "Indemnity", "description": "Indemnity insurance plan"},
    {"code": "POS", "name": "Point of Service", "description": "POS plan type"},
    {"code": "PPO", "name": "Preferred Provider Organization", "description": "PPO plan type"},
    {"code": "OTH", "name": "Other", "description": "Other plan type"}
]

# Insurance Product Types
insurance_product_types = [
    {"code": "HLT", "name": "Health", "description": "Health insurance"},
    {"code": "DEN", "name": "Dental", "description": "Dental insurance"},
    {"code": "VIS", "name": "Vision", "description": "Vision insurance"},
    {"code": "DRG", "name": "Drug", "description": "Prescription drug coverage"},
    {"code": "HOS", "name": "Hearing", "description": "Hearing aid coverage"},
    {"code": "LTC", "name": "Long Term Care", "description": "Long term care insurance"},
    {"code": "DIS", "name": "Disability", "description": "Disability insurance"},
    {"code": "LIF", "name": "Life", "description": "Life insurance"}
]

# Coordination of Benefits Codes
cob_codes = [
    {"code": "P", "status": "Primary", "description": "Primary insurance"},
    {"code": "S", "status": "Secondary", "description": "Secondary insurance"},
    {"code": "T", "status": "Tertiary", "description": "Tertiary insurance"},
    {"code": "U", "status": "Unknown", "description": "Unknown coordination"}
]

# Relationship Codes
relationship_codes = [
    {"code": "01", "relationship": "Self", "description": "Patient is the subscriber"},
    {"code": "02", "relationship": "Spouse", "description": "Patient is spouse of subscriber"},
    {"code": "03", "relationship": "Natural Child", "description": "Patient is natural child"},
    {"code": "04", "relationship": "Natural Child, Insured has no Financial Responsibility", "description": "Natural child, no financial responsibility"},
    {"code": "05", "relationship": "Step Child", "description": "Patient is step child"},
    {"code": "06", "relationship": "Foster Child", "description": "Patient is foster child"},
    {"code": "07", "relationship": "Ward of the Court", "description": "Patient is ward of court"},
    {"code": "08", "relationship": "Employee", "description": "Patient is employee"},
    {"code": "09", "relationship": "Unknown", "description": "Relationship unknown"},
    {"code": "10", "relationship": "Handicapped Dependent", "description": "Handicapped dependent"},
    {"code": "11", "relationship": "Organ Donor", "description": "Organ donor"},
    {"code": "12", "relationship": "Cadaver Donor", "description": "Cadaver donor"},
    {"code": "13", "relationship": "Grandchild", "description": "Patient is grandchild"},
    {"code": "14", "relationship": "Niece/Nephew", "description": "Patient is niece or nephew"},
    {"code": "15", "relationship": "Injured Plaintiff", "description": "Injured plaintiff"},
    {"code": "16", "relationship": "Sponsored Dependent", "description": "Sponsored dependent"},
    {"code": "17", "relationship": "Minor Dependent of Minor Dependent", "description": "Minor dependent of minor dependent"},
    {"code": "18", "relationship": "Parent", "description": "Patient is parent"},
    {"code": "19", "relationship": "Grandparent", "description": "Patient is grandparent"},
    {"code": "20", "relationship": "Domestic Partner", "description": "Domestic partner"},
    {"code": "21", "relationship": "Other Relationship", "description": "Other relationship"},
    {"code": "39", "relationship": "Organ Donor", "description": "Organ donor"}
]

# Practice Types - From pVerify API Documentation
practice_types = [
    {"id": "3", "practice_type": "DME"},
    {"id": "8", "practice_type": "Chemotherapy"},
    {"id": "9", "practice_type": "VisionOptometry"},
    {"id": "12", "practice_type": "Physical Therapy"},
    {"id": "17", "practice_type": "Primary Care"},
    {"id": "18", "practice_type": "Specialist - Office"},
    {"id": "21", "practice_type": "Mental Health"},
    {"id": "22", "practice_type": "Surgical -Office"},
    {"id": "23", "practice_type": "Urgent Care"},
    {"id": "24", "practice_type": "Diagnostic Lab"},
    {"id": "27", "practice_type": "Specialist(Office)_Surgical(Office)_Diagnostic Lab"},
    {"id": "28", "practice_type": "ASC Facility"},
    {"id": "30", "practice_type": "Chiropractic"},
    {"id": "31", "practice_type": "MRI/CAT Scan"},
    {"id": "32", "practice_type": "X-Ray"},
    {"id": "33", "practice_type": "Speech Therapy"},
    {"id": "34", "practice_type": "Occupational Therapy"},
    {"id": "35", "practice_type": "ASC_Specialist(Office)_VisionOptometry"},
    {"id": "36", "practice_type": "Specialist(Office)_Chemotherapy"},
    {"id": "37", "practice_type": "Physical Therapy_Chiropractic"},
    {"id": "38", "practice_type": "Physical Therapy_DME"},
    {"id": "39", "practice_type": "Physical Therapy_Occupational Therapy_DME"},
    {"id": "40", "practice_type": "Physical Therapy_Occupational Therapy_Speech Therapy"},
    {"id": "41", "practice_type": "Specialist(Office)_VisionOptometry"},
    {"id": "42", "practice_type": "Specialist(Office)_DME"},
    {"id": "43", "practice_type": "Specialist(Office)_Surgical(Office)"},
    {"id": "44", "practice_type": "Specialist(Office)_ASC Facility"},
    {"id": "45", "practice_type": "Physical Therapy_XRay"},
    {"id": "46", "practice_type": "XRay_MRI/CAT Scan"},
    {"id": "53", "practice_type": "Speech Therapy_Occupational Therapy"},
    {"id": "54", "practice_type": "Emergency Services"},
    {"id": "55", "practice_type": "Routine Physical"},
    {"id": "56", "practice_type": "Podiatry Office"},
    {"id": "57", "practice_type": "Professional - Outpatient Physician"},
    {"id": "58", "practice_type": "Anesthesia"},
    {"id": "59", "practice_type": "Substance Abuse"},
    {"id": "60", "practice_type": "Substance Abuse Facility-InPatient"},
    {"id": "61", "practice_type": "Substance Abuse Facility-OutPatient"},
    {"id": "62", "practice_type": "Telemedicine"},
    {"id": "63", "practice_type": "Flu Vaccination"},
    {"id": "64", "practice_type": "Mental Health_Sub Abuse Professional"},
    {"id": "65", "practice_type": "Mental Health_Sub Abuse_In&OutFacility"},
    {"id": "66", "practice_type": "Sub Abuse_In&OutFacility"},
    {"id": "67", "practice_type": "Mental Health_SubAbuse_In-NetFacility"},
    {"id": "68", "practice_type": "Specialist(Office)_ASC_Professional OutPatient"},
    {"id": "69", "practice_type": "ASC Facility_Professional OutPatient"},
    {"id": "70", "practice_type": "General_Office_Benefits(30)"},
    {"id": "71", "practice_type": "Podiatry_XRay_DME"},
    {"id": "72", "practice_type": "Podiatry_DME"},
    {"id": "73", "practice_type": "Hospital-InPatient"},
    {"id": "74", "practice_type": "Emergency Services_Hospital-InPatient"},
    {"id": "75", "practice_type": "Speech Therapy_Occupational Therapy_MentalHealth"},
    {"id": "76", "practice_type": "DME_Diagnostic Lab"},
    {"id": "77", "practice_type": "Pharmacy"},
    {"id": "78", "practice_type": "Specialist(Office)_Pharmacy"},
    {"id": "79", "practice_type": "Physical Therapy_Occupational Therapy_Mental Health"},
    {"id": "80", "practice_type": "Specialist(Office)_DME_ASC Facility"},
    {"id": "81", "practice_type": "Specialist(Office)_DME_Surgical(Office)"},
    {"id": "82", "practice_type": "Specialist(Office)_DME_Hospital-OutPatient"},
    {"id": "83", "practice_type": "Hospital-OutPatient"},
    {"id": "84", "practice_type": "Physical Therapy_Occupational Therapy"},
    {"id": "85", "practice_type": "Specialist(Office)_Surgery(Office)_DME"},
    {"id": "87", "practice_type": "SpecialistOffice_DME_X-Ray"},
    {"id": "88", "practice_type": "SpecialistOffice_Physical Therapy"},
    {"id": "89", "practice_type": "Telemedicine-Primary Care"},
    {"id": "90", "practice_type": "Telemedicine-Specialist Services"},
    {"id": "91", "practice_type": "Telemedicine-Urgent Care"},
    {"id": "92", "practice_type": "Telemedicine-Physical Therapy"},
    {"id": "93", "practice_type": "Telemedicine-Mental Health"},
    {"id": "94", "practice_type": "Psychotherapy"},
    {"id": "95", "practice_type": "Telemedicine Primary + Telemedicine Specialist"},
    {"id": "96", "practice_type": "Telemedicine Primary + Telemedicine Specialist+Telemedicine Urgent care"},
    {"id": "97", "practice_type": "Specialist(Office)_Psychotherapy"},
    {"id": "100", "practice_type": "Hospital-Outpatient_Surgical(Office)_Specialist(Office)"},
    {"id": "101", "practice_type": "SNF(AG)"},
    {"id": "102", "practice_type": "SNF-Room_and_Board(AH)"},
    {"id": "103", "practice_type": "SNF_SNF-Room_and_Board"},
    {"id": "104", "practice_type": "Specialist(Office)_Mental Health"},
    {"id": "105", "practice_type": "Specialist(office)_Primary Care_Chiropractic"},
    {"id": "106", "practice_type": "Occupational Therapy_DME"},
    {"id": "107", "practice_type": "Professional (Physician) Visit - Inpatient(99)"},
    {"id": "108", "practice_type": "Home Health Care(42)"},
    {"id": "109", "practice_type": "Hospice(45)"},
    {"id": "110", "practice_type": "Home Health (42)_Hospice (45)"},
    {"id": "111", "practice_type": "Mental Health_Telemedicine- Mental Health (MH)"},
    {"id": "112", "practice_type": "Allergies"},
    {"id": "113", "practice_type": "Diagnostic Medical"},
    {"id": "114", "practice_type": "Maternity"},
    {"id": "115", "practice_type": "Immunizations"},
    {"id": "116", "practice_type": "Primary Care_Diagnostic Lab"},
    {"id": "117", "practice_type": "Routine Physical_Immunizations_Diagnostic Medical"},
    {"id": "118", "practice_type": "Physical Therapy & Telemedicine physical therapy"},
    {"id": "119", "practice_type": "Telemedicine-Occupational Therapy(AD)"},
    {"id": "120", "practice_type": "Telemedicine-Speech Therapy(AF)"},
    {"id": "121", "practice_type": "Occupational Therapy & Telemedicine Occupational Therapy"},
    {"id": "122", "practice_type": "Speech Therapy & Telemedicine Speech Therapy"},
    {"id": "123", "practice_type": "PrimaryCare_Immunizations_Diagnostic Lab"},
    {"id": "124", "practice_type": "PrimaryCare_Immunizations_Diagnostic Medical"},
    {"id": "125", "practice_type": "Physical Therapy_Mental Health"},
    {"id": "126", "practice_type": "Radiation Therapy"},
    {"id": "127", "practice_type": "Specialist(Office)_Chemotherapy_RadiationTherapy"},
    {"id": "130", "practice_type": "Infertility(83)"},
    {"id": "131", "practice_type": "Allergy Testing(79)"},
    {"id": "132", "practice_type": "Specialist Office(98)_Allergy Testing(79)"},
    {"id": "133", "practice_type": "Specialist Office(98)_Infertility(83)"},
    {"id": "134", "practice_type": "In-vitro Fertilization(61)"},
    {"id": "135", "practice_type": "In-vitro Fertilization(61)_Infertility(83)_Specialist Office(98)"},
    {"id": "136", "practice_type": "Psychiatric (A4)"},
    {"id": "137", "practice_type": "Mental Health_Telemedicine-Mental Health(MH)_Psychotherapy(A6)_Psychiatric (A4)"},
    {"id": "138", "practice_type": "Primary Care (30)_Urgent Care (UC)_Diagnostic Lab (5)"},
    {"id": "139", "practice_type": "SNF(AG)_SNF-RoomAndBoard(AH)_PhysicalTherapy(PT)"},
    {"id": "140", "practice_type": "Acupuncture(64)"},
    {"id": "141", "practice_type": "Acupuncture(64)_PhysicalTherapy(PT)"},
    {"id": "142", "practice_type": "Gynecological(BT)"},
    {"id": "143", "practice_type": "Obstetrical(BU)"},
    {"id": "144", "practice_type": "Obstetrical/Gynecological(BV)"},
    {"id": "145", "practice_type": "Family Planning(82)"},
    {"id": "146", "practice_type": "Surgical Benefits-Professional Physician(CC)"},
    {"id": "147", "practice_type": "Surgical Benefits-Facility(CD)"},
    {"id": "148", "practice_type": "GeneralOfficeBenefits_Maternity"},
    {"id": "149", "practice_type": "Dialysis(76)"},
    {"id": "150", "practice_type": "Mental Health Facility-Outpatient(CH)"},
    {"id": "151", "practice_type": "SpecialistOffice_DME_X-Ray_Surgical(office)"},
    {"id": "152", "practice_type": "Mental Health_SubAbuse_Out Net Facility"},
    {"id": "153", "practice_type": "Mental Health_Mental Health OP Facility _Sub_Abuse_In&Out Net Facility"},
    {"id": "154", "practice_type": "Mental Health (MH)_Mental Health Facility Outpatient(CH)"},
    {"id": "155", "practice_type": "Telemedicine-Primary Care (30)_Diagnostic Medical (73)_Allergy Testing (79)"},
    {"id": "156", "practice_type": "Primary Care(30)_Routine Physical(81)"},
    {"id": "157", "practice_type": "XRay (4)_VisionOptometry (AL)"},
    {"id": "158", "practice_type": "Diagnostic Medical(73)_Allergy Testing(79)_Specialist Office Visit(98)"}
]

# pVerify Complete Payer Codes - From Excel File (pVerifyPayerDetail_08312021PlusVision.xlsx)
# Total: 1513 payers including EDI, NON EDI, Dental, and Vision payers
# Leading zeros are preserved in payer codes
# Distribution: EDI (1063), NON EDI (251), Dental (181), NON EDI ADV PAYER (10), EDI Delayed (8)

# NOTE: Due to the large size of the complete payer list (1513 entries),
# this file shows a representative sample. For the complete implementation,
# you would include all 1513 entries from the Excel file.

# Sample of major payers with leading zeros preserved
pverify_major_payers = [
    {"payer_code": "00001", "payer_name": "Aetna", "type": "EDI", "eligibility": "Yes", "claim_status": "Yes"},
    {"payer_code": "00002", "payer_name": "Blue Cross of California", "type": "EDI", "eligibility": "Yes", "claim_status": "Yes"},
    {"payer_code": "00003", "payer_name": "Blue Shield of California", "type": "EDI", "eligibility": "Yes", "claim_status": "No"},
    {"payer_code": "00004", "payer_name": "Cigna", "type": "EDI", "eligibility": "Yes", "claim_status": "Yes"},
    {"payer_code": "00007", "payer_name": "Medicare Part A and B", "type": "EDI", "eligibility": "Yes", "claim_status": "No"},
    {"payer_code": "00112", "payer_name": "Humana", "type": "EDI", "eligibility": "Yes", "claim_status": "Yes"},
    {"payer_code": "00165", "payer_name": "Ohio Medicaid", "type": "EDI", "eligibility": "Yes", "claim_status": "Yes"},
    {"payer_code": "00192", "payer_name": "United Healthcare", "type": "EDI", "eligibility": "Yes", "claim_status": "Yes"},
    {"payer_code": "00220", "payer_name": "Blue Cross Blue Shield Texas", "type": "EDI", "eligibility": "Yes", "claim_status": "Yes"},
    {"payer_code": "00283", "payer_name": "AARP (A United HealthCare Insurance Company)", "type": "EDI", "eligibility": "Yes", "claim_status": "Yes"}
]

# Sample from actual Excel file showing variety of payer types
pverify_excel_sample = [
    {"payer_code": "BO00017", "payer_name": "47198 BO", "type": "NON EDI", "eligibility": "Yes", "claim_status": "No"},
    {"payer_code": "00283", "payer_name": "AARP (A United HealthCare Insurance Company)", "type": "EDI", "eligibility": "Yes", "claim_status": "Yes"},
    {"payer_code": "DE001", "payer_name": "AARP Dental", "type": "Dental", "eligibility": "Yes", "claim_status": "No"},
    {"payer_code": "00344", "payer_name": "Absolute Total Care", "type": "EDI", "eligibility": "Yes", "claim_status": "Yes"},
    {"payer_code": "BO10061", "payer_name": "ACCESS IPA BO", "type": "NON EDI", "eligibility": "Yes", "claim_status": "No"},
    {"payer_code": "BO00018", "payer_name": "ACCESS IPA-BO", "type": "NON EDI", "eligibility": "Yes", "claim_status": "No"},
    {"payer_code": "000903", "payer_name": "Access Medicare", "type": "EDI", "eligibility": "Yes", "claim_status": "No"},
    {"payer_code": "01410", "payer_name": "Acclaim Inc", "type": "EDI", "eligibility": "Yes", "claim_status": "No"},
    {"payer_code": "000947", "payer_name": "ACS Benefit Services", "type": "EDI", "eligibility": "Yes", "claim_status": "No"},
    {"payer_code": "BO00013", "payer_name": "Adavanced Primary Care Network BO", "type": "NON EDI", "eligibility": "Yes", "claim_status": "No"}
]

